// Diagnostic probe: reads test fixtures and emits annotated TDEF hex dumps to
// docs/design/*-format-probe-appendix.md. One-shot research tool; not part of
// the shipping library. See docs/design/index-and-relationship-format-notes.md
// and docs/design/complex-columns-format-notes.md for what these dumps validate.

using System.Globalization;
using System.Text;
using JetDatabaseWriter;
using JetDatabaseWriter.Internal;

string repoRoot = FindRepoRoot();
string fixtures = Path.Combine(repoRoot, "JetDatabaseWriter.Tests", "Databases");
string designDir = Path.Combine(repoRoot, "docs", "design");

await WriteIndexAppendixAsync(
    Path.Combine(fixtures, "NorthwindTraders.accdb"),
    Path.Combine(designDir, "format-probe-appendix-index.md"));

await WriteComplexAppendixAsync(
    Path.Combine(fixtures, "ComplexFields.accdb"),
    Path.Combine(designDir, "format-probe-appendix-complex.md"));

Console.WriteLine("Done.");
return 0;

static string FindRepoRoot()
{
    string? d = AppContext.BaseDirectory;
    while (d != null && !File.Exists(Path.Combine(d, "JetDatabaseReader.slnx")))
        d = Path.GetDirectoryName(d);
    return d ?? throw new InvalidOperationException("Could not locate repo root (JetDatabaseReader.slnx).");
}

static async Task WriteIndexAppendixAsync(string fixturePath, string outPath)
{
    Console.WriteLine($"Probing {Path.GetFileName(fixturePath)} ...");
    await using var reader = await AccessReader.OpenAsync(fixturePath);
    var catalog = await ReadCatalogAsync(reader);

    var sb = new StringBuilder();
    sb.AppendLine($"# Format probe appendix: indexes, PKs, FKs, relationships");
    sb.AppendLine();
    sb.AppendLine($"Source fixture: `JetDatabaseWriter.Tests/Databases/{Path.GetFileName(fixturePath)}`");
    sb.AppendLine($"Generated by: `JetDatabaseWriter.FormatProbe` on {DateTimeOffset.UtcNow:u}");
    sb.AppendLine($"Format: {reader.DatabaseFormat}, page size: {reader.PageSize}");
    sb.AppendLine();
    sb.AppendLine("This appendix is regenerated by re-running `dotnet run --project JetDatabaseWriter.FormatProbe`.");
    sb.AppendLine("It exists to ground the offset claims in [`index-and-relationship-format-notes.md`](index-and-relationship-format-notes.md) against real Access-produced bytes rather than the partial mdbtools spec.");
    sb.AppendLine();

    // Catalog summary
    sb.AppendLine("## Catalog summary (all `MSysObjects` rows)");
    sb.AppendLine();
    sb.AppendLine("| Id | Name | Type | Flags (hex) | TDEF page |");
    sb.AppendLine("|---:|---|---:|---|---:|");
    foreach (var c in catalog.OrderBy(c => c.Id))
        sb.AppendLine($"| {c.Id} | `{Md(c.Name)}` | {c.Type} | 0x{unchecked((uint)c.Flags):X8} | {c.TdefPage} |");
    sb.AppendLine();

    // Tables of interest: pick anything with indexes plus a few catalog tables.
    // Note: NorthwindTraders.accdb has NO MSysIndexes/MSysIndexColumns catalog tables —
    // index metadata in modern ACCDB lives ONLY in TDEF blocks. Confirms a key correction
    // to docs/design/index-and-relationship-format-notes.md §6.
    string[] alwaysInclude = ["MSysObjects", "MSysIndexes", "MSysIndexColumns",
                              "MSysRelationships", "MSysComplexColumns", "MSysQueries"];

    var picked = new HashSet<long>();
    foreach (string name in alwaysInclude)
    {
        var match = catalog.FirstOrDefault(c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase));
        if (match.TdefPage > 0 && picked.Add(match.TdefPage))
            await EmitTDefAsync(reader, sb, match.Name, match.TdefPage, includeIndexAnnotations: true);
    }

    // Pick up to 4 user tables (no system mask) that actually have indexes
    int userTablesEmitted = 0;
    foreach (var c in catalog
        .Where(c => c.Type == 1 && unchecked((uint)c.Flags & 0x80000000u) == 0 && c.TdefPage > 0)
        .OrderBy(c => c.Id))
    {
        if (userTablesEmitted >= 6) break;
        if (picked.Contains(c.TdefPage)) continue;
        byte[]? td = await reader.GetRawTDefBytesAsync(c.TdefPage, default);
        if (td is null) continue;
        int numIdx = (int)U32(td, 47);
        if (numIdx == 0) continue;
        picked.Add(c.TdefPage);
        await EmitTDefAsync(reader, sb, c.Name, c.TdefPage, includeIndexAnnotations: true);
        userTablesEmitted++;
    }

    Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
    await File.WriteAllTextAsync(outPath, sb.ToString());
    Console.WriteLine($"Wrote {outPath}");
}

static async Task WriteComplexAppendixAsync(string fixturePath, string outPath)
{
    Console.WriteLine($"Probing {Path.GetFileName(fixturePath)} ...");
    await using var reader = await AccessReader.OpenAsync(fixturePath);
    var catalog = await ReadCatalogAsync(reader);

    var sb = new StringBuilder();
    sb.AppendLine($"# Format probe appendix: complex columns (Attachment, Multi-value)");
    sb.AppendLine();
    sb.AppendLine($"Source fixture: `JetDatabaseWriter.Tests/Databases/{Path.GetFileName(fixturePath)}`");
    sb.AppendLine($"Generated by: `JetDatabaseWriter.FormatProbe` on {DateTimeOffset.UtcNow:u}");
    sb.AppendLine($"Format: {reader.DatabaseFormat}, page size: {reader.PageSize}");
    sb.AppendLine();
    sb.AppendLine("Regenerate with `dotnet run --project JetDatabaseWriter.FormatProbe`. See [`complex-columns-format-notes.md`](complex-columns-format-notes.md) for the unverified spec this appendix grounds.");
    sb.AppendLine();

    // Catalog summary
    sb.AppendLine("## Catalog summary (all `MSysObjects` rows)");
    sb.AppendLine();
    sb.AppendLine("| Id | Name | Type | Flags (hex) | TDEF page |");
    sb.AppendLine("|---:|---|---:|---|---:|");
    foreach (var c in catalog.OrderBy(c => c.Id))
        sb.AppendLine($"| {c.Id} | `{Md(c.Name)}` | {c.Type} | 0x{unchecked((uint)c.Flags):X8} | {c.TdefPage} |");
    sb.AppendLine();

    // Find every table with a complex column, plus MSysComplexColumns,
    // every flat table (`f_*` naming convention), every type/template table (`MSysComplexType_*`).
    var hits = new List<(string Name, long Page, string Reason)>();

    foreach (var c in catalog.Where(c => c.Type == 1 && c.TdefPage > 0))
    {
        byte[]? bytes = await reader.GetRawTDefBytesAsync(c.TdefPage, default);
        if (bytes is null) continue;
        bool hasComplex = HasComplexColumn(bytes, reader.DatabaseFormat);
        if (hasComplex && !c.Name.StartsWith("f_", StringComparison.Ordinal))
            hits.Add((c.Name, c.TdefPage, "parent table — has T_ATTACHMENT (0x11) or T_COMPLEX (0x12) column"));
    }

    foreach (var c in catalog.Where(c => c.Name.Equals("MSysComplexColumns", StringComparison.OrdinalIgnoreCase)))
        hits.Insert(0, (c.Name, c.TdefPage, "catalog: `MSysComplexColumns` schema"));

    foreach (var c in catalog.Where(c => c.Type == 1 && c.Name.StartsWith("MSysComplexType_", StringComparison.Ordinal)))
        hits.Add((c.Name, c.TdefPage, "complex-type template table (Jackcess `typeObjTable`)"));

    foreach (var c in catalog.Where(c => c.Type == 1 && c.Name.StartsWith("f_", StringComparison.Ordinal)))
        hits.Add((c.Name, c.TdefPage, "hidden flat (child) table — `f_<guid>_<userColName>`"));

    foreach (var hit in hits.DistinctBy(h => h.Page))
    {
        sb.AppendLine($"### Reason: {hit.Reason}");
        await EmitTDefAsync(reader, sb, hit.Name, hit.Page, includeIndexAnnotations: false, includeComplexAnnotations: true);
    }

    Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
    await File.WriteAllTextAsync(outPath, sb.ToString());
    Console.WriteLine($"Wrote {outPath}");
}

static async Task<List<(long Id, string Name, int Type, long Flags, long TdefPage)>> ReadCatalogAsync(AccessReader reader)
{
    var msys = await reader.GetMSysObjectsTableDefAsync(default)
               ?? throw new InvalidOperationException("MSysObjects TDEF not found.");
    int idxId = msys.Columns.FindIndex(c => string.Equals(c.Name, "Id", StringComparison.OrdinalIgnoreCase));
    int idxName = msys.Columns.FindIndex(c => string.Equals(c.Name, "Name", StringComparison.OrdinalIgnoreCase));
    int idxType = msys.Columns.FindIndex(c => string.Equals(c.Name, "Type", StringComparison.OrdinalIgnoreCase));
    int idxFlags = msys.Columns.FindIndex(c => string.Equals(c.Name, "Flags", StringComparison.OrdinalIgnoreCase));

    var result = new List<(long Id, string Name, int Type, long Flags, long TdefPage)>();
    await foreach (var row in reader.EnumerateMSysObjectsRowsAsync(msys, default))
    {
        long id = ParseLong(SafeGet(row, idxId));
        string name = SafeGet(row, idxName);
        int type = (int)ParseLong(SafeGet(row, idxType));
        long flags = ParseLong(SafeGet(row, idxFlags));
        long page = id & 0x00FFFFFFL;
        result.Add((id, name, type, flags, page));
    }
    return result;
}

static string SafeGet(System.Collections.Generic.List<string> row, int i) =>
    i >= 0 && i < row.Count ? row[i] ?? string.Empty : string.Empty;

static long ParseLong(string s) =>
    long.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out long v) ? v : 0;

static bool HasComplexColumn(byte[] td, DatabaseFormat fmt)
{
    if (fmt == DatabaseFormat.Jet3Mdb) return false;
    int numCols = U16(td, 45);
    int numRealIdx = (int)U32(td, 51);
    if (numCols < 0 || numCols > 4096 || numRealIdx < 0 || numRealIdx > 1000) return false;
    int colStart = 63 + (numRealIdx * 12);
    if (colStart + (numCols * 25) > td.Length) return false;
    for (int i = 0; i < numCols; i++)
    {
        byte t = td[colStart + (i * 25)];
        if (t == 0x11 || t == 0x12) return true;
    }
    return false;
}

static async Task EmitTDefAsync(
    AccessReader reader, StringBuilder sb, string name, long page,
    bool includeIndexAnnotations = false, bool includeComplexAnnotations = false)
{
    byte[]? bytes = await reader.GetRawTDefBytesAsync(page, default);
    if (bytes is null)
    {
        sb.AppendLine($"## `{Md(name)}` — TDEF page {page}");
        sb.AppendLine();
        sb.AppendLine("> ⚠️ TDEF read failed (page is not type 0x02).");
        sb.AppendLine();
        return;
    }

    bool jet4 = reader.DatabaseFormat != DatabaseFormat.Jet3Mdb;
    int blockEnd = jet4 ? 63 : 43;
    int realIdxEntrySz = jet4 ? 12 : 8;
    int colDescSz = jet4 ? 25 : 18;
    int numColsOff = jet4 ? 45 : 25;
    int numIdxOff = jet4 ? 47 : 27;
    int numRealIdxOff = jet4 ? 51 : 31;

    int numCols = U16(bytes, numColsOff);
    int numIdx = (int)U32(bytes, numIdxOff);
    int numRealIdx = (int)U32(bytes, numRealIdxOff);

    sb.AppendLine($"## `{Md(name)}` — TDEF page {page}");
    sb.AppendLine();
    sb.AppendLine($"- TDEF total bytes (after page-chain stitch): **{bytes.Length}**");
    sb.AppendLine($"- `num_cols` (offset {numColsOff}, 2 bytes): **{numCols}**");
    sb.AppendLine($"- `num_idx` (offset {numIdxOff}, 4 bytes): **{numIdx}**");
    sb.AppendLine($"- `num_real_idx` (offset {numRealIdxOff}, 4 bytes): **{numRealIdx}**");
    if (jet4)
    {
        long ctAutonum = U32(bytes, 28);
        sb.AppendLine($"- `ct_autonum` (Jet4 only, offset 28, 4 bytes): **{ctAutonum}** — next ConceptualTableID for this table's complex columns");
    }
    sb.AppendLine();

    int colStart = blockEnd + (numRealIdx * realIdxEntrySz);
    int namesStart = colStart + (numCols * colDescSz);
    int realIdxDescStart = -1;
    int logicalIdxStart = -1;
    int logicalIdxNamesStart = -1;

    // Walk column names to find where they end. Then real-idx physical descriptors begin.
    int pos = namesStart;
    var colNames = new List<string>(numCols);
    for (int i = 0; i < numCols; i++)
    {
        if (jet4)
        {
            if (pos + 2 > bytes.Length) break;
            int len = U16(bytes, pos); pos += 2;
            if (pos + len > bytes.Length) break;
            colNames.Add(Encoding.Unicode.GetString(bytes, pos, len));
            pos += len;
        }
        else
        {
            if (pos >= bytes.Length) break;
            int len = bytes[pos++];
            if (pos + len > bytes.Length) break;
            colNames.Add(Encoding.GetEncoding(reader.CodePage).GetString(bytes, pos, len));
            pos += len;
        }
    }
    int afterColNames = pos;

    // Real-idx physical descriptor block: numRealIdx × 52 (Jet4) / 39 (Jet3)
    if (numRealIdx > 0)
    {
        realIdxDescStart = afterColNames;
        int physSz = jet4 ? 52 : 39;
        logicalIdxStart = realIdxDescStart + (numRealIdx * physSz);
    }
    else
    {
        logicalIdxStart = afterColNames;
    }

    // Logical-idx entries: numIdx × 28 (Jet4) / 20 (Jet3)
    int logicalEntrySz = jet4 ? 28 : 20;
    int afterLogicalIdx = logicalIdxStart + (numIdx * logicalEntrySz);
    if (numIdx > 0) logicalIdxNamesStart = afterLogicalIdx;

    sb.AppendLine($"### Section offsets (computed)");
    sb.AppendLine();
    sb.AppendLine("| Section | Start | Size | End (excl) |");
    sb.AppendLine("|---|---:|---:|---:|");
    sb.AppendLine($"| Page header | 0 | 8 | 8 |");
    sb.AppendLine($"| TDEF block ({(jet4 ? "Jet4: 55" : "Jet3: 35")} bytes) | 8 | {blockEnd - 8} | {blockEnd} |");
    sb.AppendLine($"| Real-idx skip entries (numRealIdx × {realIdxEntrySz}) | {blockEnd} | {numRealIdx * realIdxEntrySz} | {colStart} |");
    sb.AppendLine($"| Column descriptors (numCols × {colDescSz}) | {colStart} | {numCols * colDescSz} | {namesStart} |");
    sb.AppendLine($"| Column names (length-prefixed) | {namesStart} | {afterColNames - namesStart} | {afterColNames} |");
    if (numRealIdx > 0)
        sb.AppendLine($"| Real-idx physical descriptors (numRealIdx × {(jet4 ? 52 : 39)}) | {realIdxDescStart} | {numRealIdx * (jet4 ? 52 : 39)} | {logicalIdxStart} |");
    if (numIdx > 0)
    {
        sb.AppendLine($"| Logical-idx entries (numIdx × {logicalEntrySz}) | {logicalIdxStart} | {numIdx * logicalEntrySz} | {afterLogicalIdx} |");
        sb.AppendLine($"| Logical-idx names | {logicalIdxNamesStart} | (variable) | (computed by walk) |");
    }
    sb.AppendLine($"| Variable trailing block (per-var-col page ptrs) | (after names) | (variable, terminated by col_num=0xFFFF) | — |");
    sb.AppendLine();

    sb.AppendLine("### Column descriptors");
    sb.AppendLine();
    sb.AppendLine("| # | Name | Type (hex) | Type meaning | col_num | offset_F | col_len | flags (hex) | misc (hex, 4 bytes) |");
    sb.AppendLine("|---:|---|---|---|---:|---:|---:|---|---|");
    for (int i = 0; i < numCols && i < colNames.Count; i++)
    {
        int o = colStart + (i * colDescSz);
        if (o + colDescSz > bytes.Length) break;
        byte type = bytes[o + 0];
        int colNum = jet4 ? U16(bytes, o + 5) : U16(bytes, o + 1);
        int offF = jet4 ? U16(bytes, o + 21) : U16(bytes, o + 14);
        int colLen = jet4 ? U16(bytes, o + 23) : U16(bytes, o + 16);
        byte flags = jet4 ? bytes[o + 15] : bytes[o + 13];
        string misc4 = jet4
            ? Hex(bytes, o + 11, 4)  // misc(2) + misc_ext(2) — for complex cols this is the 4-byte ComplexID
            : Hex(bytes, o + 9, 4);
        sb.AppendLine($"| {i} | `{Md(colNames[i])}` | 0x{type:X2} | {TypeName(type)} | {colNum} | {offF} | {colLen} | 0x{flags:X2} | `{misc4}` |");
    }
    sb.AppendLine();

    if (includeComplexAnnotations)
    {
        var complexCols = new List<(int Idx, string Name, byte Type, string ComplexId)>();
        for (int i = 0; i < numCols && i < colNames.Count; i++)
        {
            int o = colStart + (i * colDescSz);
            if (o + colDescSz > bytes.Length) break;
            byte type = bytes[o + 0];
            if (type == 0x11 || type == 0x12)
            {
                string id = jet4 ? Hex(bytes, o + 11, 4) : Hex(bytes, o + 9, 4);
                complexCols.Add((i, colNames[i], type, id));
            }
        }
        if (complexCols.Count > 0)
        {
            sb.AppendLine("**Complex columns detected:**");
            sb.AppendLine();
            foreach (var (i, n, t, id) in complexCols)
                sb.AppendLine($"- Column #{i} `{Md(n)}` — type 0x{t:X2} ({TypeName(t)}) — ComplexID bytes (LE u32 in misc): `{id}` = **{(uint)U32FromHex(id)}**");
            sb.AppendLine();
        }
    }

    if (includeIndexAnnotations && numRealIdx > 0)
    {
        sb.AppendLine("### Real-index physical descriptors (raw bytes per entry)");
        sb.AppendLine();
        int physSz = jet4 ? 52 : 39;
        for (int i = 0; i < numRealIdx; i++)
        {
            int start = realIdxDescStart + (i * physSz);
            if (start + physSz > bytes.Length) break;
            sb.AppendLine($"#### Real-idx #{i} (offset {start}, {physSz} bytes)");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.Append(HexDump(bytes, start, physSz, baseOffset: start));
            sb.AppendLine("```");
            // Best-effort field decode per index-and-relationship-format-notes.md §3.1.
            if (jet4)
            {
                sb.AppendLine($"- bytes  0..3  unknown(4): `{Hex(bytes, start + 0, 4)}`");
                sb.AppendLine($"- bytes  4..33 col_map (10 × {{col_num(2),col_order(1)}}):");
                for (int slot = 0; slot < 10; slot++)
                {
                    int so = start + 4 + (slot * 3);
                    int cn = U16(bytes, so);
                    byte order = bytes[so + 2];
                    if (cn != 0xFFFF)
                        sb.AppendLine($"    - slot {slot}: col_num={cn}, col_order=0x{order:X2}");
                }
                sb.AppendLine($"- bytes 34..37 used_pages: {U32(bytes, start + 34)}");
                sb.AppendLine($"- bytes 38..41 first_dp:   {U32(bytes, start + 38)}");
                sb.AppendLine($"- byte  42     flags:       0x{bytes[start + 42]:X2}");
                sb.AppendLine($"- bytes 43..51 unknown(9): `{Hex(bytes, start + 43, 9)}`");
            }
            sb.AppendLine();
        }

        if (numIdx > 0)
        {
            sb.AppendLine("### Logical-index entries (raw bytes per entry)");
            sb.AppendLine();
            for (int i = 0; i < numIdx; i++)
            {
                int start = logicalIdxStart + (i * logicalEntrySz);
                if (start + logicalEntrySz > bytes.Length) break;
                sb.AppendLine($"#### Logical-idx #{i} (offset {start}, {logicalEntrySz} bytes)");
                sb.AppendLine();
                sb.AppendLine("```");
                sb.Append(HexDump(bytes, start, logicalEntrySz, baseOffset: start));
                sb.AppendLine("```");
                if (jet4)
                {
                    sb.AppendLine($"- bytes  0..3  unknown(4):    `{Hex(bytes, start + 0, 4)}`");
                    sb.AppendLine($"- bytes  4..7  index_num:     {U32(bytes, start + 4)}");
                    sb.AppendLine($"- bytes  8..11 index_num2:    {U32(bytes, start + 8)}");
                    sb.AppendLine($"- byte  12     rel_tbl_type:  0x{bytes[start + 12]:X2}");
                    sb.AppendLine($"- bytes 13..16 rel_idx_num:   {unchecked((int)U32(bytes, start + 13))} (0xFFFFFFFF = not a FK)");
                    sb.AppendLine($"- bytes 17..20 rel_tbl_page:  {U32(bytes, start + 17)}");
                    sb.AppendLine($"- byte  21     cascade_ups:   0x{bytes[start + 21]:X2}");
                    sb.AppendLine($"- byte  22     cascade_dels:  0x{bytes[start + 22]:X2}");
                    sb.AppendLine($"- byte  23     index_type:    0x{bytes[start + 23]:X2}  (0x01=PK, 0x02=FK)");
                    sb.AppendLine($"- bytes 24..27 trailing(4):   `{Hex(bytes, start + 24, 4)}`");
                }
                sb.AppendLine();
            }

            // Logical-idx names
            sb.AppendLine("### Logical-index names (raw)");
            sb.AppendLine();
            int npos = logicalIdxNamesStart;
            for (int i = 0; i < numIdx; i++)
            {
                if (jet4)
                {
                    if (npos + 2 > bytes.Length) break;
                    int len = U16(bytes, npos);
                    sb.AppendLine($"- #{i} (offset {npos}): len={len} → `{Encoding.Unicode.GetString(bytes, npos + 2, Math.Min(len, bytes.Length - npos - 2))}`");
                    npos += 2 + len;
                }
                else
                {
                    if (npos >= bytes.Length) break;
                    int len = bytes[npos];
                    sb.AppendLine($"- #{i} (offset {npos}): len={len} → `{Encoding.GetEncoding(reader.CodePage).GetString(bytes, npos + 1, Math.Min(len, bytes.Length - npos - 1))}`");
                    npos += 1 + len;
                }
            }
            sb.AppendLine();
        }
    }

    sb.AppendLine("### Full TDEF hex dump");
    sb.AppendLine();
    sb.AppendLine("```");
    sb.Append(HexDump(bytes, 0, bytes.Length, baseOffset: 0));
    sb.AppendLine("```");
    sb.AppendLine();
}

static string HexDump(byte[] bytes, int offset, int len, int baseOffset)
{
    var sb = new StringBuilder();
    int end = offset + len;
    for (int i = offset; i < end; i += 16)
    {
        sb.Append($"{baseOffset + (i - offset),6:X4}  ");
        for (int j = 0; j < 16; j++)
        {
            int idx = i + j;
            if (idx < end)
                sb.Append($"{bytes[idx]:X2} ");
            else
                sb.Append("   ");
            if (j == 7) sb.Append(' ');
        }
        sb.Append(' ');
        for (int j = 0; j < 16; j++)
        {
            int idx = i + j;
            if (idx < end)
            {
                byte b = bytes[idx];
                sb.Append(b is >= 0x20 and < 0x7F ? (char)b : '.');
            }
        }
        sb.AppendLine();
    }
    return sb.ToString();
}

static string Hex(byte[] b, int o, int len)
{
    var sb = new StringBuilder(len * 3);
    for (int i = 0; i < len && o + i < b.Length; i++)
        sb.Append($"{b[o + i]:X2} ");
    return sb.ToString().TrimEnd();
}

static uint U32FromHex(string spaced)
{
    string compact = spaced.Replace(" ", "");
    if (compact.Length < 8) return 0;
    byte b0 = Convert.ToByte(compact.Substring(0, 2), 16);
    byte b1 = Convert.ToByte(compact.Substring(2, 2), 16);
    byte b2 = Convert.ToByte(compact.Substring(4, 2), 16);
    byte b3 = Convert.ToByte(compact.Substring(6, 2), 16);
    return (uint)(b0 | (b1 << 8) | (b2 << 16) | (b3 << 24));
}

static int U16(byte[] b, int o) => b[o] | (b[o + 1] << 8);
static long U32(byte[] b, int o) => unchecked((uint)(b[o] | (b[o + 1] << 8) | (b[o + 2] << 16) | (b[o + 3] << 24)));
static string Md(string s) => s.Replace("|", "\\|").Replace("`", "\\`");

static string TypeName(byte t) => t switch
{
    0x01 => "BOOL", 0x02 => "BYTE", 0x03 => "INT", 0x04 => "LONG",
    0x05 => "MONEY", 0x06 => "FLOAT", 0x07 => "DOUBLE", 0x08 => "DATETIME",
    0x09 => "BINARY", 0x0A => "TEXT", 0x0B => "OLE", 0x0C => "MEMO",
    0x0F => "GUID", 0x10 => "NUMERIC", 0x11 => "ATTACHMENT (complex)",
    0x12 => "COMPLEX (multi-value/version)", _ => "?"
};
