namespace JetDatabaseWriter.Scaffold;

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Globalization;
using JetDatabaseWriter.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <summary>
/// Generates C# source code for an entity model from column metadata using Roslyn.
/// </summary>
internal static class EntityEmitter
{
    private static readonly FrozenDictionary<Type, string> FriendlyTypeNames = new Dictionary<Type, string>
    {
        [typeof(bool)] = "bool",
        [typeof(byte)] = "byte",
        [typeof(short)] = "short",
        [typeof(int)] = "int",
        [typeof(long)] = "long",
        [typeof(float)] = "float",
        [typeof(double)] = "double",
        [typeof(decimal)] = "decimal",
        [typeof(string)] = "string",
        [typeof(DateTime)] = "DateTime",
        [typeof(DateTimeOffset)] = "DateTimeOffset",
        [typeof(TimeSpan)] = "TimeSpan",
        [typeof(Guid)] = "Guid",
        [typeof(byte[])] = "byte[]",
        [typeof(object)] = "object",
    }.ToFrozenDictionary();

    private static readonly SyntaxTriviaList FileTriviaPlain = TriviaList(
        Comment("// <auto-generated />"),
        ElasticLineFeed);

    private static readonly SyntaxTriviaList FileTriviaWithNullable = TriviaList(
        Comment("// <auto-generated />"),
        ElasticLineFeed,
        Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), isActive: true)),
        ElasticLineFeed);

    public static string Emit(
        string className,
        IReadOnlyList<ColumnMetadata> columns,
        string ns,
        bool useRecords,
        bool nullable)
        => Emit(className, columns, [], ns, useRecords, nullable);

    public static string Emit(
        string className,
        IReadOnlyList<ColumnMetadata> columns,
        IReadOnlyList<ScaffoldNavigation> navigations,
        string ns,
        bool useRecords,
        bool nullable)
    {
        TypeDeclarationSyntax typeDecl = useRecords
            ? RecordDeclaration(Token(SyntaxKind.RecordKeyword), className)
                .WithOpenBraceToken(Token(SyntaxKind.OpenBraceToken))
                .WithCloseBraceToken(Token(SyntaxKind.CloseBraceToken))
            : ClassDeclaration(className);

        typeDecl = typeDecl.AddModifiers(
            Token(SyntaxKind.PublicKeyword),
            Token(SyntaxKind.SealedKeyword));

        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (ColumnMetadata col in columns)
        {
            string propName = DeduplicateName(NameCleaner.ToPropertyName(col.Name), usedNames);

            if (propName == className)
            {
                propName += "Value";
                usedNames.Add(propName);
            }

            typeDecl = typeDecl.AddMembers(BuildProperty(propName, col, nullable));
        }

        bool anyCollection = false;
        foreach (ScaffoldNavigation nav in navigations)
        {
            string navName = DeduplicateName(nav.PreferredName, usedNames);
            if (navName == className)
            {
                navName = DeduplicateName(navName + "Navigation", usedNames);
            }

            typeDecl = typeDecl.AddMembers(nav.IsCollection
                ? BuildCollectionNav(navName, nav.TargetClassName)
                : BuildReferenceNav(navName, nav.TargetClassName, nullable));
            anyCollection = anyCollection || nav.IsCollection;
        }

        FileScopedNamespaceDeclarationSyntax nsDecl = FileScopedNamespaceDeclaration(ParseName(ns))
            .AddUsings(UsingDirective(ParseName("System")));

        if (anyCollection)
        {
            nsDecl = nsDecl.AddUsings(UsingDirective(ParseName("System.Collections.Generic")));
        }

        foreach (string extraNamespace in CollectColumnNamespaces(columns))
        {
            nsDecl = nsDecl.AddUsings(UsingDirective(ParseName(extraNamespace)));
        }

        nsDecl = nsDecl.AddMembers(typeDecl);

        CompilationUnitSyntax compilationUnit = CompilationUnit()
            .AddMembers(nsDecl)
            .WithLeadingTrivia(nullable ? FileTriviaWithNullable : FileTriviaPlain);

        return FormatOutput(compilationUnit.NormalizeWhitespace().ToFullString());
    }

    private static string DeduplicateName(string name, HashSet<string> usedNames)
    {
        string baseName = name;
        for (int suffix = 2; !usedNames.Add(name); suffix++)
        {
            name = baseName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return name;
    }

    private static SortedSet<string> CollectColumnNamespaces(IReadOnlyList<ColumnMetadata> columns)
    {
        // Collects the non-System namespaces of the column CLR types so the generated file
        // imports them (for example JetDatabaseWriter.Models for a Hyperlink column);
        // without these usings the emitted entity would not compile.
        var namespaces = new SortedSet<string>(StringComparer.Ordinal);
        foreach (ColumnMetadata col in columns)
        {
            Type type = Nullable.GetUnderlyingType(col.ClrType) ?? col.ClrType;
            if (type.IsArray)
            {
                type = type.GetElementType() ?? type;
            }

            string? namespaceName = type.Namespace;
            if (namespaceName is not null
                && namespaceName != "System"
                && !namespaceName.StartsWith("System.", StringComparison.Ordinal))
            {
                namespaces.Add(namespaceName);
            }
        }

        return namespaces;
    }

    private static PropertyDeclarationSyntax BuildProperty(string name, ColumnMetadata col, bool nullable)
    {
        PropertyDeclarationSyntax property = PropertyDeclaration(ParseTypeName(MapClrType(col.ClrType, col.IsNullable, nullable)), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)));

        if (DefaultInitializer(col.ClrType, col.IsNullable, nullable) is { } initializer)
        {
            property = property
                .WithInitializer(EqualsValueClause(initializer))
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
        }

        return property.WithLeadingTrivia(
            Trivia(XmlDocSummary($"Column: {col}.")),
            ElasticLineFeed);
    }

    private static PropertyDeclarationSyntax BuildReferenceNav(string name, string targetType, bool nullable)
    {
        string type = nullable ? targetType + "?" : targetType;
        return PropertyDeclaration(ParseTypeName(type), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
            .WithLeadingTrivia(
                Trivia(XmlDocSummary($"Navigation: the related {targetType} (parent).")),
                ElasticLineFeed);
    }

    private static PropertyDeclarationSyntax BuildCollectionNav(string name, string targetType)
        => PropertyDeclaration(ParseTypeName($"ICollection<{targetType}>"), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
            .WithInitializer(EqualsValueClause(ParseExpression($"new List<{targetType}>()")))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(
                Trivia(XmlDocSummary($"Navigation: related {targetType} children.")),
                ElasticLineFeed);

    private static string FormatOutput(string source)
    {
        const string eol = "\r\n";

        source = source
            .Replace(eol + "namespace ", eol + eol + "namespace ", StringComparison.Ordinal)
            .Replace(eol + "    /// <summary>", eol + eol + "    /// <summary>", StringComparison.Ordinal)
            .Replace("{" + eol + eol + "    /// <summary>", "{" + eol + "    /// <summary>", StringComparison.Ordinal);

        int usingIdx = source.IndexOf(";" + eol + "using ", StringComparison.Ordinal);
        if (usingIdx >= 0)
        {
            source = source.Insert(usingIdx + 1 + eol.Length, eol);
        }

        return source.TrimEnd('\r', '\n') + eol;
    }

    private static string MapClrType(Type clrType, bool isNullable, bool nullableEnabled)
    {
        if (Nullable.GetUnderlyingType(clrType) is not null)
        {
            return GetFriendlyTypeName(clrType);
        }

        string baseName = GetFriendlyTypeName(clrType);
        return isNullable && (nullableEnabled || clrType.IsValueType)
            ? baseName + "?"
            : baseName;
    }

    private static string GetFriendlyTypeName(Type type)
    {
        if (FriendlyTypeNames.TryGetValue(type, out string? name))
        {
            return name;
        }

        return Nullable.GetUnderlyingType(type) is { } underlying
            ? GetFriendlyTypeName(underlying) + "?"
            : type.Name;
    }

    private static ExpressionSyntax? DefaultInitializer(Type clrType, bool isNullable, bool nullableEnabled)
    {
        if (isNullable || !nullableEnabled || clrType.IsValueType)
        {
            return null;
        }

        if (clrType == typeof(string))
        {
            return MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                PredefinedType(Token(SyntaxKind.StringKeyword)),
                IdentifierName("Empty"));
        }

        if (clrType == typeof(byte[]))
        {
            return InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("Array"),
                    GenericName(Identifier("Empty"))
                        .WithTypeArgumentList(
                            TypeArgumentList(
                                SingletonSeparatedList<TypeSyntax>(
                                    PredefinedType(Token(SyntaxKind.ByteKeyword)))))));
        }

        return PostfixUnaryExpression(
            SyntaxKind.SuppressNullableWarningExpression,
            LiteralExpression(SyntaxKind.DefaultLiteralExpression));
    }

    private static DocumentationCommentTriviaSyntax XmlDocSummary(string text) => DocumentationCommentTrivia(
            SyntaxKind.SingleLineDocumentationCommentTrivia,
            List(new XmlNodeSyntax[]
            {
                XmlText().WithTextTokens(TokenList(
                    XmlTextLiteral(
                        TriviaList(DocumentationCommentExterior("///")),
                        " ",
                        " ",
                        TriviaList()))),
                XmlElement(
                    XmlElementStartTag(XmlName("summary")),
                    SingletonList<XmlNodeSyntax>(XmlText(text)),
                    XmlElementEndTag(XmlName("summary"))),
                XmlText().WithTextTokens(TokenList(
                    XmlTextNewLine(TriviaList(), "\n", "\n", TriviaList()))),
            }));
}
