namespace JetDatabaseWriter.Scaffold;

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Xml;
using JetDatabaseWriter.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/// <summary>
/// Generates C# source code for an entity model from column metadata using Roslyn.
/// </summary>
internal static class EntityEmitter
{
    /// <summary>
    /// Member names a generated property or navigation cannot take: the members every
    /// class inherits from <see cref="object"/>, which a property would hide (CS0108),
    /// and the members the compiler synthesizes for a record, which a property would
    /// clash with. They are reserved in both modes, so switching to records never
    /// renames a property.
    /// </summary>
    internal static readonly FrozenSet<string> ReservedMemberNames = new[]
    {
        "Clone",
        "EqualityContract",
        "Equals",
        "GetHashCode",
        "GetType",
        "MemberwiseClone",
        "PrintMembers",
        "ReferenceEquals",
        "ToString",
    }.ToFrozenSet(StringComparer.Ordinal);

    private static readonly FrozenDictionary<Type, string> FriendlyTypeNames = new Dictionary<Type, string>
    {
        [typeof(bool)] = "bool",
        [typeof(byte)] = "byte",
        [typeof(short)] = "short",
        [typeof(int)] = "int",
        [typeof(long)] = "long",
        [typeof(float)] = "float",
        [typeof(double)] = "double",
        [typeof(decimal)] = "decimal",
        [typeof(string)] = "string",
        [typeof(DateTime)] = "DateTime",
        [typeof(DateTimeOffset)] = "DateTimeOffset",
        [typeof(TimeSpan)] = "TimeSpan",
        [typeof(Guid)] = "Guid",
        [typeof(byte[])] = "byte[]",
        [typeof(object)] = "object",
    }.ToFrozenDictionary();

    private static readonly SyntaxTriviaList FileTriviaPlain = TriviaList(
        Comment("// <auto-generated />"),
        ElasticLineFeed);

    private static readonly SyntaxTriviaList FileTriviaWithNullable = TriviaList(
        Comment("// <auto-generated />"),
        ElasticLineFeed,
        Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), isActive: true)),
        ElasticLineFeed);

    public static string Emit(
        string className,
        IReadOnlyList<ColumnMetadata> columns,
        string ns,
        bool useRecords,
        bool nullable)
        => Emit(className, columns, [], ns, useRecords, nullable);

    public static string Emit(
        string className,
        IReadOnlyList<ColumnMetadata> columns,
        IReadOnlyList<ScaffoldNavigation> navigations,
        string ns,
        bool useRecords,
        bool nullable)
        => Emit(className, className, columns, navigations, ns, useRecords, nullable);

    /// <summary>
    /// Emits the entity source for <paramref name="tableName"/>. A <c>[Table("...")]</c>
    /// attribute is emitted when <paramref name="className"/> differs from the table name, and
    /// a <c>[Column("...")]</c> attribute on every property whose name differs from its column
    /// (for example <c>LastName</c> for a <c>Last Name</c> column), so the reader and writer
    /// bind the generated type to the original names. Names that differ only in case need no
    /// attribute, because the library matches names case-insensitively. A property or
    /// navigation named like the class or a <see cref="ReservedMemberNames">reserved member</see>
    /// gets a <c>Value</c> or <c>Navigation</c> suffix, and a numeric suffix when that name is
    /// taken too. The using directives precede the namespace declaration, so a namespace segment
    /// such as <c>System</c> cannot capture them.
    /// </summary>
    /// <param name="className">The generated class name.</param>
    /// <param name="tableName">The Access table name the class maps.</param>
    /// <param name="columns">The table's columns.</param>
    /// <param name="navigations">The navigation properties to emit.</param>
    /// <param name="ns">The namespace of the generated class.</param>
    /// <param name="useRecords">Whether to emit a record instead of a class.</param>
    /// <param name="nullable">Whether to emit nullable reference type annotations.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(
        string className,
        string tableName,
        IReadOnlyList<ColumnMetadata> columns,
        IReadOnlyList<ScaffoldNavigation> navigations,
        string ns,
        bool useRecords,
        bool nullable)
    {
        bool anyMappingAttribute = false;
        TypeDeclarationSyntax typeDecl = useRecords
            ? RecordDeclaration(Token(SyntaxKind.RecordKeyword), className)
                .WithOpenBraceToken(Token(SyntaxKind.OpenBraceToken))
                .WithCloseBraceToken(Token(SyntaxKind.CloseBraceToken))
            : ClassDeclaration(className);

        typeDecl = typeDecl.AddModifiers(
            Token(SyntaxKind.PublicKeyword),
            Token(SyntaxKind.SealedKeyword));

        if (!NamesMatch(className, tableName))
        {
            typeDecl = typeDecl.AddAttributeLists(NameAttribute("Table", tableName));
            anyMappingAttribute = true;
        }

        var usedNames = new HashSet<string>(ReservedMemberNames, StringComparer.Ordinal) { className };

        foreach (ColumnMetadata col in columns)
        {
            string propName = DeduplicateName(MemberName(NameCleaner.ToPropertyName(col.Name), className, "Value"), usedNames);

            PropertyDeclarationSyntax property = BuildProperty(propName, col, nullable);
            if (!NamesMatch(propName, col.Name))
            {
                property = property.AddAttributeLists(NameAttribute("Column", col.Name));
                anyMappingAttribute = true;
            }

            typeDecl = typeDecl.AddMembers(property.WithLeadingTrivia(
                Trivia(XmlDocSummary(DocCommentText($"Column: {col}."))),
                ElasticLineFeed));
        }

        bool anyCollection = false;
        foreach (ScaffoldNavigation nav in navigations)
        {
            string navName = DeduplicateName(MemberName(nav.PreferredName, className, "Navigation"), usedNames);

            typeDecl = typeDecl.AddMembers(nav.IsCollection
                ? BuildCollectionNav(navName, nav.TargetClassName)
                : BuildReferenceNav(navName, nav.TargetClassName, nullable));
            anyCollection = anyCollection || nav.IsCollection;
        }

        List<UsingDirectiveSyntax> usings = [UsingDirective(ParseName("System"))];
        if (anyCollection)
        {
            usings.Add(UsingDirective(ParseName("System.Collections.Generic")));
        }

        if (anyMappingAttribute)
        {
            usings.Add(UsingDirective(ParseName("System.ComponentModel.DataAnnotations.Schema")));
        }

        foreach (string extraNamespace in CollectColumnNamespaces(columns))
        {
            usings.Add(UsingDirective(ParseName(extraNamespace)));
        }

        CompilationUnitSyntax compilationUnit = CompilationUnit()
            .AddUsings([.. usings])
            .AddMembers(FileScopedNamespaceDeclaration(ParseName(ns)).AddMembers(typeDecl))
            .WithLeadingTrivia(nullable ? FileTriviaWithNullable : FileTriviaPlain);

        return FormatOutput(compilationUnit.NormalizeWhitespace().ToFullString());
    }

    /// <summary>
    /// Returns the C# type names the properties for <paramref name="columns"/> spell out
    /// (such as <c>DateTime</c>, <c>Guid</c> or <c>Hyperlink</c>), leaving out keywords such
    /// as <c>int</c>. A generated class with one of these names would capture the
    /// property types of every entity in its namespace, so the class allocation reserves them.
    /// </summary>
    /// <param name="columns">The columns of the scaffolded tables.</param>
    /// <returns>The referenced type names.</returns>
    internal static IEnumerable<string> ReferencedTypeNames(IEnumerable<ColumnMetadata> columns)
    {
        foreach (ColumnMetadata col in columns)
        {
            Type type = Nullable.GetUnderlyingType(col.ClrType) ?? col.ClrType;
            if (type.IsArray)
            {
                type = type.GetElementType() ?? type;
            }

            string name = GetFriendlyTypeName(type);
            if (SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None)
            {
                yield return name;
            }
        }
    }

    /// <summary>
    /// Appends <paramref name="suffix"/> to a property or navigation name that would equal the
    /// class name (CS0542) or a <see cref="ReservedMemberNames">reserved member</see>.
    /// </summary>
    /// <param name="name">The preferred name.</param>
    /// <param name="className">The generated class name.</param>
    /// <param name="suffix"><c>Value</c> for a column property, <c>Navigation</c> for a navigation.</param>
    /// <returns>The name to de-duplicate.</returns>
    private static string MemberName(string name, string className, string suffix) =>
        name == className || ReservedMemberNames.Contains(name) ? name + suffix : name;

    private static string DeduplicateName(string name, HashSet<string> usedNames)
    {
        string baseName = name;
        for (int suffix = 2; !usedNames.Add(name); suffix++)
        {
            name = baseName + suffix.ToString(CultureInfo.InvariantCulture);
        }

        return name;
    }

    private static SortedSet<string> CollectColumnNamespaces(IReadOnlyList<ColumnMetadata> columns)
    {
        // Collects the non-System namespaces of the column CLR types so the generated file
        // imports them (for example JetDatabaseWriter.Models for a Hyperlink column);
        // without these usings the emitted entity would not compile.
        var namespaces = new SortedSet<string>(StringComparer.Ordinal);
        foreach (ColumnMetadata col in columns)
        {
            Type type = Nullable.GetUnderlyingType(col.ClrType) ?? col.ClrType;
            if (type.IsArray)
            {
                type = type.GetElementType() ?? type;
            }

            string? namespaceName = type.Namespace;
            if (namespaceName is not null
                && namespaceName != "System"
                && !namespaceName.StartsWith("System.", StringComparison.Ordinal))
            {
                namespaces.Add(namespaceName);
            }
        }

        return namespaces;
    }

    private static PropertyDeclarationSyntax BuildProperty(string name, ColumnMetadata col, bool nullable)
    {
        PropertyDeclarationSyntax property = PropertyDeclaration(ParseTypeName(MapClrType(col.ClrType, col.IsNullable, nullable)), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)));

        if (DefaultInitializer(col.ClrType, col.IsNullable, nullable) is { } initializer)
        {
            property = property
                .WithInitializer(EqualsValueClause(initializer))
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
        }

        return property;
    }

    /// <summary>
    /// Determines whether an emitted identifier already binds to an Access name without an
    /// attribute. The library compares column and table names case-insensitively.
    /// </summary>
    /// <param name="identifier">The generated C# identifier.</param>
    /// <param name="accessName">The Access table or column name.</param>
    /// <returns><see langword="true"/> when no mapping attribute is needed.</returns>
    private static bool NamesMatch(string identifier, string accessName) =>
        string.Equals(identifier, accessName, StringComparison.OrdinalIgnoreCase);

    /// <summary>Builds a <c>[Name("value")]</c> attribute list such as <c>[Column("Last Name")]</c>.</summary>
    /// <param name="attributeName">The attribute name without the <c>Attribute</c> suffix.</param>
    /// <param name="value">The name the attribute carries.</param>
    /// <returns>The attribute list.</returns>
    private static AttributeListSyntax NameAttribute(string attributeName, string value) =>
        AttributeList(SingletonSeparatedList(
            Attribute(IdentifierName(attributeName))
                .WithArgumentList(AttributeArgumentList(SingletonSeparatedList(
                    AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value))))))));

    private static PropertyDeclarationSyntax BuildReferenceNav(string name, string targetType, bool nullable)
    {
        string type = nullable ? targetType + "?" : targetType;
        return PropertyDeclaration(ParseTypeName(type), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
            .WithLeadingTrivia(
                Trivia(XmlDocSummary($"Navigation: the related {targetType} (parent).")),
                ElasticLineFeed);
    }

    private static PropertyDeclarationSyntax BuildCollectionNav(string name, string targetType)
        => PropertyDeclaration(ParseTypeName($"ICollection<{targetType}>"), name)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAccessorListAccessors(
                AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)))
            .WithInitializer(EqualsValueClause(ParseExpression($"new List<{targetType}>()")))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(
                Trivia(XmlDocSummary($"Navigation: related {targetType} children.")),
                ElasticLineFeed);

    /// <summary>
    /// Lays the normalized source out as the header comment and <c>#nullable</c> line, the
    /// using directives, the file-scoped namespace declaration and the type, each group
    /// separated by one blank line, with one blank line between members and a single final
    /// line break.
    /// </summary>
    /// <param name="source">The normalized source.</param>
    /// <returns>The laid-out source.</returns>
    private static string FormatOutput(string source)
    {
        const string eol = "\r\n";

        source = source
            .Replace(eol + "    /// <summary>", eol + eol + "    /// <summary>", StringComparison.Ordinal)
            .Replace("{" + eol + eol + "    /// <summary>", "{" + eol + "    /// <summary>", StringComparison.Ordinal)
            .Replace(eol + eol + eol + "    /// <summary>", eol + eol + "    /// <summary>", StringComparison.Ordinal);

        string[] lines = source.Split(eol);
        var output = new StringBuilder(source.Length + 16);
        int i = 0;
        for (; i < lines.Length && !IsUsing(lines[i]) && !IsNamespace(lines[i]); i++)
        {
            if (lines[i].Length > 0)
            {
                output.Append(lines[i]).Append(eol);
            }
        }

        output.Append(eol);
        for (; i < lines.Length && !IsNamespace(lines[i]); i++)
        {
            if (lines[i].Length > 0)
            {
                output.Append(lines[i]).Append(eol);
            }
        }

        output.Append(eol);
        if (i < lines.Length)
        {
            output.Append(lines[i++]).Append(eol).Append(eol);
        }

        for (; i < lines.Length && lines[i].Length == 0; i++)
        {
        }

        output.AppendJoin(eol, lines[i..]);
        return output.ToString().TrimEnd('\r', '\n') + eol;

        static bool IsUsing(string line) => line.StartsWith("using ", StringComparison.Ordinal);

        static bool IsNamespace(string line) => line.StartsWith("namespace ", StringComparison.Ordinal);
    }

    private static string MapClrType(Type clrType, bool isNullable, bool nullableEnabled)
    {
        if (Nullable.GetUnderlyingType(clrType) is not null)
        {
            return GetFriendlyTypeName(clrType);
        }

        string baseName = GetFriendlyTypeName(clrType);
        return isNullable && (nullableEnabled || clrType.IsValueType)
            ? baseName + "?"
            : baseName;
    }

    private static string GetFriendlyTypeName(Type type)
    {
        if (FriendlyTypeNames.TryGetValue(type, out string? name))
        {
            return name;
        }

        return Nullable.GetUnderlyingType(type) is { } underlying
            ? GetFriendlyTypeName(underlying) + "?"
            : type.Name;
    }

    private static ExpressionSyntax? DefaultInitializer(Type clrType, bool isNullable, bool nullableEnabled)
    {
        if (isNullable || !nullableEnabled || clrType.IsValueType)
        {
            return null;
        }

        if (clrType == typeof(string))
        {
            return MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                PredefinedType(Token(SyntaxKind.StringKeyword)),
                IdentifierName("Empty"));
        }

        // Fully qualified, because a property named Array would capture a bare Array.
        if (clrType == typeof(byte[]))
        {
            return ParseExpression("global::System.Array.Empty<byte>()");
        }

        return PostfixUnaryExpression(
            SyntaxKind.SuppressNullableWarningExpression,
            LiteralExpression(SyntaxKind.DefaultLiteralExpression));
    }

    /// <summary>
    /// Replaces each control character, such as a line break in a column name, each other
    /// character C# reads as a line break (U+2028 LINE SEPARATOR and U+2029 PARAGRAPH
    /// SEPARATOR), and each character XML cannot hold with a space, so the doc comment
    /// stays on one line and <see cref="XmlText(string)"/> accepts it.
    /// </summary>
    /// <param name="text">The text.</param>
    /// <returns>The text to put in the doc comment.</returns>
    private static string DocCommentText(string text)
    {
        char[] chars = text.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (char.IsHighSurrogate(chars[i]) && i + 1 < chars.Length && char.IsLowSurrogate(chars[i + 1]))
            {
                i++;
            }
            else if (char.IsControl(chars[i]) || SyntaxFacts.IsNewLine(chars[i]) || !XmlConvert.IsXmlChar(chars[i]))
            {
                chars[i] = ' ';
            }
        }

        return new string(chars);
    }

    private static DocumentationCommentTriviaSyntax XmlDocSummary(string text) => DocumentationCommentTrivia(
            SyntaxKind.SingleLineDocumentationCommentTrivia,
            List(new XmlNodeSyntax[]
            {
                XmlText().WithTextTokens(TokenList(
                    XmlTextLiteral(
                        TriviaList(DocumentationCommentExterior("///")),
                        " ",
                        " ",
                        TriviaList()))),
                XmlElement(
                    XmlElementStartTag(XmlName("summary")),
                    SingletonList<XmlNodeSyntax>(XmlText(text)),
                    XmlElementEndTag(XmlName("summary"))),
                XmlText().WithTextTokens(TokenList(
                    XmlTextNewLine(TriviaList(), "\r\n", "\r\n", TriviaList()))),
            }));
}
