namespace JetDatabaseWriter.Tests.Scaffold;

using System;
using System.Collections.Generic;

using JetDatabaseWriter.Scaffold;

using Xunit;

public class EntityEmitterTests
{
    private static List<ColumnMetadata> SimpleColumns =>
    [
        new ColumnMetadata { Name = "Id", ClrType = typeof(int), IsNullable = false, TypeName = "Long Integer", Size = ColumnSize.FromBytes(4) },
        new ColumnMetadata { Name = "Name", ClrType = typeof(string), IsNullable = true, TypeName = "Text", Size = ColumnSize.FromBytes(255) },
    ];

    [Fact]
    public void Emit_Generates_Valid_Class()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.Contains("class Customer", result, StringComparison.Ordinal);
        Assert.Contains("namespace MyApp.Models", result, StringComparison.Ordinal);
        Assert.Contains("public int Id { get; set; }", result, StringComparison.Ordinal);
        Assert.Contains("public string Name { get; set; }", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Generates_Record_When_Requested()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: true, nullable: false);

        Assert.Contains("record Customer", result, StringComparison.Ordinal);
        Assert.DoesNotContain("class Customer", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Adds_Nullable_Enable_Directive()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: true);

        Assert.Contains("#nullable enable", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Omits_Nullable_Directive_When_Disabled()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.DoesNotContain("#nullable", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Nullable_String_Uses_Question_Mark()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: true);

        Assert.Contains("string?", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_NonNullable_String_Gets_Default_With_Nullable_Enabled()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Code", ClrType = typeof(string), IsNullable = false, TypeName = "Text", Size = ColumnSize.FromBytes(50) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: true);

        Assert.Contains("string.Empty", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Nullable_Int_Appends_Question_Mark()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Score", ClrType = typeof(int), IsNullable = true, TypeName = "Long Integer", Size = ColumnSize.FromBytes(4) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("int?", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Contains_AutoGenerated_Comment()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.Contains("// <auto-generated>", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Contains_Using_System()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.Contains("using System;", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Sealed_Modifier_Present()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.Contains("public sealed class Customer", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Generates_Xml_Doc_Comments()
    {
        string result = EntityEmitter.Emit("Customer", SimpleColumns, "MyApp.Models", useRecords: false, nullable: false);

        Assert.Contains("Column: Id", result, StringComparison.Ordinal);
        Assert.Contains("Column: Name", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Deduplicates_Property_Names()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Name", ClrType = typeof(string), IsNullable = true, TypeName = "Text", Size = ColumnSize.FromBytes(50) },
            new() { Name = "Name", ClrType = typeof(string), IsNullable = true, TypeName = "Text", Size = ColumnSize.FromBytes(50) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("Name ", result, StringComparison.Ordinal);
        Assert.Contains("Name2", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Avoids_Property_Name_Collision_With_Class_Name()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Customer", ClrType = typeof(string), IsNullable = true, TypeName = "Text", Size = ColumnSize.FromBytes(50) },
        };

        string result = EntityEmitter.Emit("Customer", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("CustomerValue", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Handles_ByteArray_Type()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Photo", ClrType = typeof(byte[]), IsNullable = false, TypeName = "OLE Object", Size = ColumnSize.Lval },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: true);

        Assert.Contains("byte[]", result, StringComparison.Ordinal);
        Assert.Contains("Array.Empty<byte>()", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Handles_DateTime_Type()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "Created", ClrType = typeof(DateTime), IsNullable = false, TypeName = "Date/Time", Size = ColumnSize.FromBytes(8) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("DateTime Created", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Handles_Guid_Type()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "UniqueId", ClrType = typeof(Guid), IsNullable = false, TypeName = "GUID", Size = ColumnSize.FromBytes(16) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("Guid UniqueId", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Handles_Boolean_Type()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "IsActive", ClrType = typeof(bool), IsNullable = false, TypeName = "Yes/No", Size = ColumnSize.FromBits(1) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("bool IsActive", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Empty_Columns_Produces_Empty_Class()
    {
        string result = EntityEmitter.Emit("Empty", new List<ColumnMetadata>(), "NS", useRecords: false, nullable: false);

        Assert.Contains("public sealed class Empty", result, StringComparison.Ordinal);
        Assert.DoesNotContain("get; set;", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Handles_Special_Characters_In_Column_Name()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "A<B>C&D", ClrType = typeof(string), IsNullable = true, TypeName = "Text", Size = ColumnSize.FromBytes(50) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("ABCD", result, StringComparison.Ordinal);
        Assert.Contains("Column:", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Emit_Maps_All_Friendly_Types_Correctly()
    {
        var columns = new List<ColumnMetadata>
        {
            new() { Name = "A", ClrType = typeof(short), IsNullable = false, TypeName = "Integer", Size = ColumnSize.FromBytes(2) },
            new() { Name = "B", ClrType = typeof(long), IsNullable = false, TypeName = "Big Integer", Size = ColumnSize.FromBytes(8) },
            new() { Name = "C", ClrType = typeof(float), IsNullable = false, TypeName = "Single", Size = ColumnSize.FromBytes(4) },
            new() { Name = "D", ClrType = typeof(double), IsNullable = false, TypeName = "Double", Size = ColumnSize.FromBytes(8) },
            new() { Name = "E", ClrType = typeof(decimal), IsNullable = false, TypeName = "Decimal", Size = ColumnSize.FromBytes(16) },
            new() { Name = "F", ClrType = typeof(byte), IsNullable = false, TypeName = "Byte", Size = ColumnSize.FromBytes(1) },
        };

        string result = EntityEmitter.Emit("Item", columns, "NS", useRecords: false, nullable: false);

        Assert.Contains("short A", result, StringComparison.Ordinal);
        Assert.Contains("long B", result, StringComparison.Ordinal);
        Assert.Contains("float C", result, StringComparison.Ordinal);
        Assert.Contains("double D", result, StringComparison.Ordinal);
        Assert.Contains("decimal E", result, StringComparison.Ordinal);
        Assert.Contains("byte F", result, StringComparison.Ordinal);
    }
}
