name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/JetDatabaseWriter/JetDatabaseWriter.csproj

      - name: Build
        run: dotnet build ${{ github.workspace }}/JetDatabaseWriter/JetDatabaseWriter.csproj -c Release --no-restore

      - name: Create NuGet package
        run: dotnet pack ${{ github.workspace }}/JetDatabaseWriter/JetDatabaseWriter.csproj -c Release --no-build -o ${{ github.workspace }}/nupkg

      - name: List files (debug)
        run: dir ${{ github.workspace }}\nupkg

      - name: Push to NuGet.org
        run: dotnet nuget push "${{ github.workspace }}\nupkg\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
